backend:
  name: git-gateway
  branch: master
  repo: ryanalencar/decap-poc
publish_mode: editorial_workflow
media_folder: "images/uploads"
locale: "pt"
show_preview_links: true
search: true
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: docs
    label: Documentações
    label_singular: "Documentação"
    folder: content
    create: true
    nested:
      depth: 100
      summary: "{{title}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta:
      {
        path:
          {
            widget: select,
            label: "Página",
            options:
              [
                { label: "Ágil", value: "agil" },
                { label: "Arquitetura", value: "arquitetura" },
                { label: "Catalogo", value: "catalogo" },
              ],
            index_file: "_index",
          },
      }
